{
    "assignee": null,
    "assignees": [],
    "body": "Since Cython 0.24, I'm seeing a compilation failure on code that's using `cython.view.array` to dynamically create typed memoryviews. Here's the end of the traceback I get (full code to reproduce and full traceback are at the end of this report):\r\n\r\n```\r\nCompiler crash traceback from this point on:\r\n  File \"/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/Cython/Compiler/ExprNodes.py\", line 1783, in compile_time_value\r\n    return denv.lookup(self.name)\r\nAttributeError: 'NoneType' object has no attribute 'lookup'\r\n```\r\n\r\nThe failure seems very similar to that reported in April 2016 on the cython-devel mailing list, in a message entitled \"Cython compiler crash in 0.24\": https://mail.python.org/pipermail/cython-devel/2016-April/004771.html\r\n\r\nVersions in use: Cython 0.25.2-1, Python 2.7.12, OS X 10.9.5.\r\n\r\n--- \r\n\r\nHere's a cut-down version of the original code (and yes, the original code made more sense than this):\r\n\r\n```\r\n(test)bash-3.2$ cat view_array_compile_failure.pyx \r\ncimport cython\r\ncimport numpy as np\r\nimport numpy as np\r\n\r\ncdef double _safe_interp(\r\n        double x,\r\n        double[::1] xp,\r\n        double[::1] fp,\r\n        size_t n,\r\n    ):\r\n    return 1.3\r\n\r\ndef convert(object depth_to_time):\r\n    sample_count = 16\r\n\r\n    native_trace = cython.view.array(\r\n        shape=(sample_count,),\r\n        itemsize=sizeof(double),\r\n        format='d',\r\n    )\r\n\r\n    return np.zeros(16, dtype=np.float64)\r\n```\r\n\r\nUnder Cython < 0.24, this compiles without error. Under Cython 0.24 and later, I get a traceback like the following:\r\n```\r\n(test)bash-3.2$ cythonize view_array_compile_failure.pyx \r\nCompiling /Users/mdickinson/Desktop/view_array_compile_failure.pyx because it changed.\r\n[1/1] Cythonizing /Users/mdickinson/Desktop/view_array_compile_failure.pyx\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\ndef convert(object depth_to_time):\r\n    sample_count = 16\r\n\r\n    native_trace = cython.view.array(\r\n        shape=(sample_count,),\r\n                          ^\r\n------------------------------------------------------------\r\n\r\nview_array_compile_failure.pyx:17:27: Compiler crash in TransformBuiltinMethods\r\n\r\nModuleNode.body = StatListNode(view_array_compile_failure.pyx:1:0)\r\nStatListNode.stats[4] = StatListNode(view_array_compile_failure.pyx:13:0)\r\nStatListNode.stats[0] = DefNode(view_array_compile_failure.pyx:13:0,\r\n    modifiers = [...]/0,\r\n    name = u'convert',\r\n    num_required_args = 1,\r\n    py_wrapper_required = True,\r\n    reqd_kw_flags_cname = '0')\r\nDefNode.body = StatListNode(view_array_compile_failure.pyx:14:4,\r\n    is_terminator = True)\r\nStatListNode.stats[1] = SingleAssignmentNode(view_array_compile_failure.pyx:16:36)\r\nSingleAssignmentNode.rhs = GeneralCallNode(view_array_compile_failure.pyx:16:36,\r\n    result_is_used = True,\r\n    use_managed_ref = True)\r\nFile 'ExprNodes.py', line 8158, in compile_time_value: DictNode(view_array_compile_failure.pyx:17:13,\r\n    is_dict_literal = True,\r\n    is_temp = 1,\r\n    obj_conversion_errors = [...]/0,\r\n    reject_duplicates = True,\r\n    result_is_used = True,\r\n    use_managed_ref = True)\r\nFile 'ExprNodes.py', line 7457, in compile_time_value: TupleNode(view_array_compile_failure.pyx:17:15,\r\n    is_sequence_constructor = 1,\r\n    result_is_used = True,\r\n    use_managed_ref = True)\r\nFile 'ExprNodes.py', line 6853, in compile_time_value_list: TupleNode(view_array_compile_failure.pyx:17:15,\r\n    is_sequence_constructor = 1,\r\n    result_is_used = True,\r\n    use_managed_ref = True)\r\nFile 'ExprNodes.py', line 1785, in compile_time_value: NameNode(view_array_compile_failure.pyx:17:27,\r\n    cf_maybe_null = True,\r\n    is_name = True,\r\n    name = u'sample_count',\r\n    result_is_used = True,\r\n    use_managed_ref = True)\r\n\r\nCompiler crash traceback from this point on:\r\n  File \"/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/Cython/Compiler/ExprNodes.py\", line 1783, in compile_time_value\r\n    return denv.lookup(self.name)\r\nAttributeError: 'NoneType' object has no attribute 'lookup'\r\nTraceback (most recent call last):\r\n  File \"/Users/mdickinson/.edm/envs/test/bin/cythonize\", line 10, in <module>\r\n    sys.exit(main())\r\n  File \"/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/Cython/Build/Cythonize.py\", line 196, in main\r\n    cython_compile(path, options)\r\n  File \"/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/Cython/Build/Cythonize.py\", line 90, in cython_compile\r\n    **options.options)\r\n  File \"/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/Cython/Build/Dependencies.py\", line 934, in cythonize\r\n    cythonize_one(*args)\r\n  File \"/Users/mdickinson/.edm/envs/test/lib/python2.7/site-packages/Cython/Build/Dependencies.py\", line 1056, in cythonize_one\r\n    raise CompileError(None, pyx_file)\r\nCython.Compiler.Errors.CompileError: /Users/mdickinson/Desktop/view_array_compile_failure.pyx\r\n```",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1598/comments",
    "created_at": "2017-02-03T15:12:02Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/662003?v=3",
                "events_url": "https://api.github.com/users/mdickinson/events{/privacy}",
                "followers_url": "https://api.github.com/users/mdickinson/followers",
                "following_url": "https://api.github.com/users/mdickinson/following{/other_user}",
                "gists_url": "https://api.github.com/users/mdickinson/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mdickinson",
                "id": 662003,
                "login": "mdickinson",
                "organizations_url": "https://api.github.com/users/mdickinson/orgs",
                "received_events_url": "https://api.github.com/users/mdickinson/received_events",
                "repos_url": "https://api.github.com/users/mdickinson/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mdickinson/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mdickinson/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mdickinson"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-02-03T15:31:14Z",
            "event": "referenced",
            "id": 948221789,
            "url": "https://api.github.com/repos/cython/cython/issues/events/948221789"
        },
        {
            "actor": {
                "avatar_url": "https://avatars.githubusercontent.com/u/662003?v=3",
                "events_url": "https://api.github.com/users/mdickinson/events{/privacy}",
                "followers_url": "https://api.github.com/users/mdickinson/followers",
                "following_url": "https://api.github.com/users/mdickinson/following{/other_user}",
                "gists_url": "https://api.github.com/users/mdickinson/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/mdickinson",
                "id": 662003,
                "login": "mdickinson",
                "organizations_url": "https://api.github.com/users/mdickinson/orgs",
                "received_events_url": "https://api.github.com/users/mdickinson/received_events",
                "repos_url": "https://api.github.com/users/mdickinson/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/mdickinson/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mdickinson/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/mdickinson"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2017-02-03T16:46:52Z",
            "event": "referenced",
            "id": 948345698,
            "url": "https://api.github.com/repos/cython/cython/issues/events/948345698"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1598/events",
    "html_url": "https://github.com/cython/cython/issues/1598",
    "id": 205182955,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1598/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1598,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Compiler crash with cython.view.array: 'NoneType' object has no attribute 'lookup'",
    "updated_at": "2017-02-03T15:14:08Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1598",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/662003?v=3",
        "events_url": "https://api.github.com/users/mdickinson/events{/privacy}",
        "followers_url": "https://api.github.com/users/mdickinson/followers",
        "following_url": "https://api.github.com/users/mdickinson/following{/other_user}",
        "gists_url": "https://api.github.com/users/mdickinson/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/mdickinson",
        "id": 662003,
        "login": "mdickinson",
        "organizations_url": "https://api.github.com/users/mdickinson/orgs",
        "received_events_url": "https://api.github.com/users/mdickinson/received_events",
        "repos_url": "https://api.github.com/users/mdickinson/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/mdickinson/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/mdickinson/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/mdickinson"
    }
}