{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "On macOS 10.12.4, Cython 0.25.2, Python 3.6.1, if you await asyncio.sleep() <= Cython <= Python chain, it will segfault. It won't die if you await Cython future right away, without first using Python.\r\n\r\nHere is an example that reproduces this bug:\r\n\r\nmain.py:\r\n```\r\nWANT_CRASH = True\r\n\r\nimport asyncio\r\nimport cy_test\r\n\r\nasync def main():\r\n    await cy_test.say()\r\n\r\nloop = asyncio.get_event_loop()\r\n\r\nif WANT_CRASH:\r\n    loop.run_until_complete(main())\r\nelse:\r\n    loop.run_until_complete(cy_test.say())\r\n\r\nloop.close()\r\n```\r\n\r\ncy_test.pyx:\r\n```\r\nimport asyncio\r\nfrom py_test import py_async\r\n\r\nasync def cy_async():\r\n    print(\"- this one is from Cython\")\r\n\r\nasync def say():\r\n    await cb()\r\n\r\nasync def cb(): # renaming this to \"say\" would prevent crash\r\n    print(\"Async functions can be awaited without problem:\")\r\n    await cy_async()\r\n    await py_async()\r\n    print(\"And this will actually sleep for 3 seconds before crashing\")\r\n    await asyncio.sleep(3)\r\n    print(\"I will be never output, because app has crashed already\")\r\n```\r\n\r\npy_test.py:\r\n```\r\nasync def py_async():\r\n    print(\"- and this one is from Python\")\r\n```\r\n\r\nSetup.py:\r\n```\r\nfrom distutils.core import setup\r\nfrom distutils.extension import Extension\r\nfrom Cython.Build import cythonize\r\n\r\nsetup(\r\n    name='asyncio_cb',\r\n    ext_modules=cythonize([\r\n        Extension(\"cy_test\", [\"cy_test.pyx\"]),\r\n    ]),\r\n)\r\n```\r\n\r\nMakefile:\r\n```\r\nall:\r\n\tpython3 Setup.py build_ext --inplace\r\n\r\ntest:\tall\r\n\tpython3 main.py\r\n\r\nclean:\r\n\t@echo Cleaning\r\n\t@rm -f cy_*.c *.o *.so *~ core\r\n\t@rm -rf build\r\n```\r\n",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "NONE",
            "body": "Maybe there is a typo in filename:   `py_test.pyx` should be `py_test.py`",
            "created_at": "2018-02-10T14:05:20Z",
            "html_url": "https://github.com/cython/cython/issues/1685#issuecomment-364657444",
            "id": 364657444,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1685",
            "updated_at": "2018-02-10T14:05:20Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/364657444",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/413970?v=4",
                "events_url": "https://api.github.com/users/chenfengyuan/events{/privacy}",
                "followers_url": "https://api.github.com/users/chenfengyuan/followers",
                "following_url": "https://api.github.com/users/chenfengyuan/following{/other_user}",
                "gists_url": "https://api.github.com/users/chenfengyuan/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chenfengyuan",
                "id": 413970,
                "login": "chenfengyuan",
                "organizations_url": "https://api.github.com/users/chenfengyuan/orgs",
                "received_events_url": "https://api.github.com/users/chenfengyuan/received_events",
                "repos_url": "https://api.github.com/users/chenfengyuan/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chenfengyuan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chenfengyuan/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chenfengyuan"
            }
        },
        {
            "author_association": "OWNER",
            "body": "Is this still an issue with latest master?\r\nCould be that 3cd1e3da1766246b6b2fb053e651c1a2bed382b7 fixed it already.",
            "created_at": "2018-02-11T09:19:43Z",
            "html_url": "https://github.com/cython/cython/issues/1685#issuecomment-364736352",
            "id": 364736352,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1685",
            "updated_at": "2018-02-11T09:19:43Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/364736352",
            "user": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            }
        },
        {
            "author_association": "NONE",
            "body": "@chenfengyuan updated issue to fix that typo.",
            "created_at": "2018-02-11T23:50:19Z",
            "html_url": "https://github.com/cython/cython/issues/1685#issuecomment-364802073",
            "id": 364802073,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1685",
            "updated_at": "2018-02-11T23:50:19Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/364802073",
            "user": {
                "avatar_url": "https://avatars1.githubusercontent.com/u/14891625?v=4",
                "events_url": "https://api.github.com/users/toriningen/events{/privacy}",
                "followers_url": "https://api.github.com/users/toriningen/followers",
                "following_url": "https://api.github.com/users/toriningen/following{/other_user}",
                "gists_url": "https://api.github.com/users/toriningen/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/toriningen",
                "id": 14891625,
                "login": "toriningen",
                "organizations_url": "https://api.github.com/users/toriningen/orgs",
                "received_events_url": "https://api.github.com/users/toriningen/received_events",
                "repos_url": "https://api.github.com/users/toriningen/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/toriningen/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toriningen/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/toriningen"
            }
        },
        {
            "author_association": "NONE",
            "body": "@scoder I have just checked it â€” unfortunately, latest master (0.24-1755-g829d7bbef) is still segfaulting, macOS 10.12.6, Python 3.6.4.\r\n\r\nCrashlog:\r\n```\r\nThread 0 Crashed:: Dispatch queue: com.apple.main-thread\r\n0   ???                           \t000000000000000000 0 + 0\r\n1   cy_test.cpython-36m-darwin.so \t0x000000010e612d60 __Pyx_CoroutineAwait_Next + 48\r\n2   org.python.python             \t0x000000010da8f44e _PyEval_EvalFrameDefault + 15238\r\n3   org.python.python             \t0x000000010da10d54 gen_send_ex + 214\r\n4   _asyncio.cpython-36m-darwin.so\t0x000000010e4e2e38 task_step + 446\r\n5   _asyncio.cpython-36m-darwin.so\t0x000000010e4e3bd4 task_wakeup + 346\r\n6   _asyncio.cpython-36m-darwin.so\t0x000000010e4e289e TaskWakeupMethWrapper_call + 134\r\n7   org.python.python             \t0x000000010d9f7942 PyObject_Call + 101\r\n8   org.python.python             \t0x000000010da8cdfc _PyEval_EvalFrameDefault + 5428\r\n9   org.python.python             \t0x000000010da94de3 _PyFunction_FastCall + 121\r\n10  org.python.python             \t0x000000010da93cb5 call_function + 448\r\n11  org.python.python             \t0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811\r\n12  org.python.python             \t0x000000010da94de3 _PyFunction_FastCall + 121\r\n13  org.python.python             \t0x000000010da93cb5 call_function + 448\r\n14  org.python.python             \t0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811\r\n15  org.python.python             \t0x000000010da94de3 _PyFunction_FastCall + 121\r\n16  org.python.python             \t0x000000010da93cb5 call_function + 448\r\n17  org.python.python             \t0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811\r\n18  org.python.python             \t0x000000010da94de3 _PyFunction_FastCall + 121\r\n19  org.python.python             \t0x000000010da93cb5 call_function + 448\r\n20  org.python.python             \t0x000000010da8cb93 _PyEval_EvalFrameDefault + 4811\r\n21  org.python.python             \t0x000000010da94440 _PyEval_EvalCodeWithName + 1719\r\n22  org.python.python             \t0x000000010da8b84e PyEval_EvalCode + 42\r\n23  org.python.python             \t0x000000010dab419e run_mod + 54\r\n24  org.python.python             \t0x000000010dab31bf PyRun_FileExFlags + 160\r\n25  org.python.python             \t0x000000010dab289c PyRun_SimpleFileExFlags + 285\r\n26  org.python.python             \t0x000000010dac66c0 Py_Main + 3484\r\n27  org.python.python             \t0x000000010d9e9e1d 0x10d9e8000 + 7709\r\n28  libdyld.dylib                 \t0x00007fffa1f21235 start + 1\r\n\r\nThread 0 crashed with X86 Thread State (64-bit):\r\n  rax: 0x000000010e614d18  rbx: 0x000000010e5e37b8  rcx: 0x000000010da92fa0  rdx: 0x0000000000000000\r\n  rdi: 0x000000010e5e3840  rsi: 0x0000000000000000  rbp: 0x00007fff52216b20  rsp: 0x00007fff52216b08\r\n   r8: 0x000000010e4b9420   r9: 0x000000010e4b9448  r10: 0x0000000000000007  r11: 0x00200000000437cb\r\n  r12: 0x000000010e500708  r13: 0x000000010e56b870  r14: 0x0000000000000048  r15: 0x000000010e56b760\r\n  rip: 0x0000000000000000  rfl: 0x0000000000010202  cr2: 0x0000000000000000\r\n  \r\nLogical CPU:     6\r\nError Code:      0x00000014\r\nTrap Number:     14\r\n```",
            "created_at": "2018-02-12T00:02:30Z",
            "html_url": "https://github.com/cython/cython/issues/1685#issuecomment-364803090",
            "id": 364803090,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1685",
            "updated_at": "2018-02-12T00:02:30Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/364803090",
            "user": {
                "avatar_url": "https://avatars1.githubusercontent.com/u/14891625?v=4",
                "events_url": "https://api.github.com/users/toriningen/events{/privacy}",
                "followers_url": "https://api.github.com/users/toriningen/followers",
                "following_url": "https://api.github.com/users/toriningen/following{/other_user}",
                "gists_url": "https://api.github.com/users/toriningen/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/toriningen",
                "id": 14891625,
                "login": "toriningen",
                "organizations_url": "https://api.github.com/users/toriningen/orgs",
                "received_events_url": "https://api.github.com/users/toriningen/received_events",
                "repos_url": "https://api.github.com/users/toriningen/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/toriningen/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/toriningen/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/toriningen"
            }
        },
        {
            "author_association": "NONE",
            "body": "Amazon Linux AMI release 2017.09\r\nLinux ip-172-18-1-195 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux\r\nPython 3.6.2 (default, Nov  2 2017, 19:34:31)\r\nCython==0.27.3\r\n```\r\n(gdb) bt\r\n#0  0x0000000000000000 in ?? ()\r\n#1  0x00007fffeb523eca in __Pyx_Generator_Next (self=0x7fffeb960d90) at cy_test.c:3307\r\n#2  0x00007ffff7a044f3 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0\r\n#3  0x00007ffff79749df in _PyGen_Send () from /usr/lib64/libpython3.6m.so.1.0\r\n#4  0x00007fffebc554bc in ?? () from /xxxxxxxx/venv/lib64/python3.6/lib-dynload/_asyncio.cpython-36m-x86_64-linux-gnu.so\r\n#5  0x00007fffebc55f1c in ?? () from /xxxxxxxx/venv/lib64/python3.6/lib-dynload/_asyncio.cpython-36m-x86_64-linux-gnu.so\r\n#6  0x00007ffff7963bd3 in PyObject_Call () from /usr/lib64/libpython3.6m.so.1.0\r\n#7  0x00007ffff7a006e6 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0\r\n#8  0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#9  0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#10 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0\r\n#11 0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#12 0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#13 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0\r\n#14 0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#15 0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#16 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0\r\n#17 0x00007ffff7a09eba in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#18 0x00007ffff7a0a1f3 in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#19 0x00007ffff79fe9d7 in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.6m.so.1.0\r\n#20 0x00007ffff7a0a56f in PyEval_EvalCodeEx () from /usr/lib64/libpython3.6m.so.1.0\r\n#21 0x00007ffff7a0affb in PyEval_EvalCode () from /usr/lib64/libpython3.6m.so.1.0\r\n#22 0x00007ffff7a910ae in ?? () from /usr/lib64/libpython3.6m.so.1.0\r\n#23 0x00007ffff7945839 in PyRun_FileExFlags () from /usr/lib64/libpython3.6m.so.1.0\r\n#24 0x00007ffff7945be9 in PyRun_SimpleFileExFlags () from /usr/lib64/libpython3.6m.so.1.0\r\n#25 0x00007ffff7a979bb in Py_Main () from /usr/lib64/libpython3.6m.so.1.0\r\n#26 0x0000000000400b19 in main ()\r\n(gdb)\r\n```\r\n",
            "created_at": "2018-02-12T09:33:12Z",
            "html_url": "https://github.com/cython/cython/issues/1685#issuecomment-364869810",
            "id": 364869810,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/1685",
            "updated_at": "2018-02-12T09:33:12Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/364869810",
            "user": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/413970?v=4",
                "events_url": "https://api.github.com/users/chenfengyuan/events{/privacy}",
                "followers_url": "https://api.github.com/users/chenfengyuan/followers",
                "following_url": "https://api.github.com/users/chenfengyuan/following{/other_user}",
                "gists_url": "https://api.github.com/users/chenfengyuan/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chenfengyuan",
                "id": 413970,
                "login": "chenfengyuan",
                "organizations_url": "https://api.github.com/users/chenfengyuan/orgs",
                "received_events_url": "https://api.github.com/users/chenfengyuan/received_events",
                "repos_url": "https://api.github.com/users/chenfengyuan/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chenfengyuan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chenfengyuan/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chenfengyuan"
            }
        }
    ],
    "comments": 5,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1685/comments",
    "created_at": "2017-04-25T19:51:15Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/413970?v=4",
                "events_url": "https://api.github.com/users/chenfengyuan/events{/privacy}",
                "followers_url": "https://api.github.com/users/chenfengyuan/followers",
                "following_url": "https://api.github.com/users/chenfengyuan/following{/other_user}",
                "gists_url": "https://api.github.com/users/chenfengyuan/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chenfengyuan",
                "id": 413970,
                "login": "chenfengyuan",
                "organizations_url": "https://api.github.com/users/chenfengyuan/orgs",
                "received_events_url": "https://api.github.com/users/chenfengyuan/received_events",
                "repos_url": "https://api.github.com/users/chenfengyuan/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chenfengyuan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chenfengyuan/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chenfengyuan"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2018-02-11T23:50:19Z",
            "event": "mentioned",
            "id": 1468658141,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1468658141"
        },
        {
            "actor": {
                "avatar_url": "https://avatars2.githubusercontent.com/u/413970?v=4",
                "events_url": "https://api.github.com/users/chenfengyuan/events{/privacy}",
                "followers_url": "https://api.github.com/users/chenfengyuan/followers",
                "following_url": "https://api.github.com/users/chenfengyuan/following{/other_user}",
                "gists_url": "https://api.github.com/users/chenfengyuan/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/chenfengyuan",
                "id": 413970,
                "login": "chenfengyuan",
                "organizations_url": "https://api.github.com/users/chenfengyuan/orgs",
                "received_events_url": "https://api.github.com/users/chenfengyuan/received_events",
                "repos_url": "https://api.github.com/users/chenfengyuan/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/chenfengyuan/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chenfengyuan/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/chenfengyuan"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2018-02-11T23:50:19Z",
            "event": "subscribed",
            "id": 1468658142,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1468658142"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2018-02-12T00:02:30Z",
            "event": "mentioned",
            "id": 1468662580,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1468662580"
        },
        {
            "actor": {
                "avatar_url": "https://avatars0.githubusercontent.com/u/491659?v=4",
                "events_url": "https://api.github.com/users/scoder/events{/privacy}",
                "followers_url": "https://api.github.com/users/scoder/followers",
                "following_url": "https://api.github.com/users/scoder/following{/other_user}",
                "gists_url": "https://api.github.com/users/scoder/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/scoder",
                "id": 491659,
                "login": "scoder",
                "organizations_url": "https://api.github.com/users/scoder/orgs",
                "received_events_url": "https://api.github.com/users/scoder/received_events",
                "repos_url": "https://api.github.com/users/scoder/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/scoder/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/scoder/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/scoder"
            },
            "commit_id": null,
            "commit_url": null,
            "created_at": "2018-02-12T00:02:30Z",
            "event": "subscribed",
            "id": 1468662581,
            "url": "https://api.github.com/repos/cython/cython/issues/events/1468662581"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1685/events",
    "html_url": "https://github.com/cython/cython/issues/1685",
    "id": 224252540,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1685/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1685,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "segfault with asyncio",
    "updated_at": "2018-02-12T09:33:12Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1685",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/14891625?v=4",
        "events_url": "https://api.github.com/users/toriningen/events{/privacy}",
        "followers_url": "https://api.github.com/users/toriningen/followers",
        "following_url": "https://api.github.com/users/toriningen/following{/other_user}",
        "gists_url": "https://api.github.com/users/toriningen/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/toriningen",
        "id": 14891625,
        "login": "toriningen",
        "organizations_url": "https://api.github.com/users/toriningen/orgs",
        "received_events_url": "https://api.github.com/users/toriningen/received_events",
        "repos_url": "https://api.github.com/users/toriningen/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/toriningen/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/toriningen/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/toriningen"
    }
}