{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "On mips, the `st_rdev` and `st_dev` fields of `struct stat` are of type `long unsigned int` rather than `dev_t` for $REASONS. The `posix/stat.pxd` file shipped with Cython correctly defines them as `dev_t`. To get my source code to compile under mips, I therefore thought I'd just teach Cython about this peculiarity:\r\n\r\n```\r\nfrom posix.stat cimport *\r\ncdef extern from \"<sys/stat.h>\" nogil:\r\n    cdef struct struct_mstat \"stat\":\r\n        int   st_dev\r\n        ino_t   st_ino\r\n        mode_t  st_mode\r\n        nlink_t st_nlink\r\n        uid_t   st_uid\r\n        gid_t   st_gid\r\n        int st_rdev\r\n        off_t   st_size\r\n        blksize_t st_blksize\r\n        blkcnt_t st_blocks\r\n        time_t  st_atime\r\n        time_t  st_mtime\r\n        time_t  st_ctime\r\n```\r\n\r\nHowever, this did not have any effect at all. On further investigation, renaming eg `st_ino` to `st_ino_fo` did not result in any warnings either.\r\n\r\nIt seems to me that Cython silently uses its own definition of `struct stat`, and ignores everything that attempts to re-define it. I would have expected that a more local declaration takes predecence. But even more important, I think Cython should at least warn if it encounters such a conflicting definition.\r\n\r\n\r\n",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/1874/comments",
    "created_at": "2017-09-15T13:29:59Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/1874/events",
    "html_url": "https://github.com/cython/cython/issues/1874",
    "id": 258040241,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/1874/labels{/name}",
    "locked": false,
    "milestone": null,
    "number": 1874,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "No warning on conflicting definitions",
    "updated_at": "2017-09-15T13:29:59Z",
    "url": "https://api.github.com/repos/cython/cython/issues/1874",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/701625?v=4",
        "events_url": "https://api.github.com/users/Nikratio/events{/privacy}",
        "followers_url": "https://api.github.com/users/Nikratio/followers",
        "following_url": "https://api.github.com/users/Nikratio/following{/other_user}",
        "gists_url": "https://api.github.com/users/Nikratio/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/Nikratio",
        "id": 701625,
        "login": "Nikratio",
        "organizations_url": "https://api.github.com/users/Nikratio/orgs",
        "received_events_url": "https://api.github.com/users/Nikratio/received_events",
        "repos_url": "https://api.github.com/users/Nikratio/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/Nikratio/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Nikratio/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/Nikratio"
    }
}