{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "This might be already known, but I was trying to use the technique described [in the cdef classed tutorial](http://cython.readthedocs.io/en/latest/src/tutorial/cdef_classes.html) together with fused types. However, when I try to do this I get gcc errors due to duplicate members.\r\n```python\r\ncimport cython\r\n\r\ncdef extern from \"math.h\":\r\n    double sin(double)\r\n\r\ncdef class Function:\r\n    cpdef double evaluate(self, cython.floating x) except *:\r\n        return 0\r\n\r\ncdef class SinOfSquareFunction(Function):\r\n    cpdef double evaluate(self, cython.floating x) except *:\r\n        return sin(x**2)\r\n\r\ndef integrate(Function f, double a, double b, int N):\r\n    cdef int i\r\n    cdef double s, dx\r\n    if f is None:\r\n        raise ValueError(\"f cannot be None\")\r\n    s = 0\r\n    dx = (b-a)/N\r\n    for i in range(N):\r\n        s += f.evaluate(a+i*dx)\r\n    return s * dx\r\n\r\nprint(integrate(SinOfSquareFunction(), 0, 1, 10000))\r\n```\r\n\r\nresults in the following gcc error:\r\n```\r\n$gcc -shared -pthread -fPIC -fwrapv -O2 -Wall -fno-strict-aliasing -I/usr/include/python3.6 -o testing.so testing.c\r\ntesting.c:672:12: error: duplicate member ‘__pyx_fuse_0evaluate’\r\n   double (*__pyx_fuse_0evaluate)(struct __pyx_obj_7testing_Function *, float, int __pyx_skip_dispatch);\r\n            ^~~~~~~~~~~~~~~~~~~~\r\ntesting.c:673:12: error: duplicate member ‘__pyx_fuse_1evaluate’\r\n   double (*__pyx_fuse_1evaluate)(struct __pyx_obj_7testing_Function *, double, int __pyx_skip_dispatch);\r\n            ^~~~~~~~~~~~~~~~~~~~\r\n```\r\n",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2120/comments",
    "created_at": "2018-02-25T00:43:36Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2120/events",
    "html_url": "https://github.com/cython/cython/issues/2120",
    "id": 299986084,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2120/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUyOTk5ODYwODQ=",
    "number": 2120,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Fused types do not work with extension types",
    "updated_at": "2018-02-25T00:43:36Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2120",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/1154946?v=4",
        "events_url": "https://api.github.com/users/cycomanic/events{/privacy}",
        "followers_url": "https://api.github.com/users/cycomanic/followers",
        "following_url": "https://api.github.com/users/cycomanic/following{/other_user}",
        "gists_url": "https://api.github.com/users/cycomanic/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/cycomanic",
        "id": 1154946,
        "login": "cycomanic",
        "node_id": "MDQ6VXNlcjExNTQ5NDY=",
        "organizations_url": "https://api.github.com/users/cycomanic/orgs",
        "received_events_url": "https://api.github.com/users/cycomanic/received_events",
        "repos_url": "https://api.github.com/users/cycomanic/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/cycomanic/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/cycomanic/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/cycomanic"
    }
}