{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "Given `foo.pyx`:\r\n```cython\r\ncdef class Base:\r\n    pass\r\n\r\ncdef class Derived(Base):\r\n    cdef object __weakref__\r\n```\r\n\r\nIts trivial `setup.py`:\r\n```python\r\nfrom setuptools import setup\r\nfrom Cython.Build import cythonize\r\n\r\nsetup(\r\n    name='foo',\r\n    ext_modules=cythonize('foo.pyx'),\r\n)\r\n```\r\n\r\nAnd its equally simple test `script.py`:\r\n```python\r\nfrom foo import Derived\r\nfrom weakref import ref\r\ne = Derived()\r\nr = ref(e)\r\ndel e\r\ndel r\r\n```\r\n\r\nUnder Python 3.7b4 this will crash:\r\n```\r\nThread 0 Crashed:: Dispatch queue: com.apple.main-thread\r\n0   libsystem_kernel.dylib        \t0x00007fff51ecab6e __pthread_kill + 10\r\n1   libsystem_pthread.dylib       \t0x00007fff52095080 pthread_kill + 333\r\n2   libsystem_c.dylib             \t0x00007fff51dd86fe raise + 26\r\n3   libsystem_platform.dylib      \t0x00007fff52088f5a _sigtramp + 26\r\n4   ???                           \t0xcbcbcbcbcbcbcbcb 0 + 14685055086129564619\r\n5   org.python.python             \t0x00000001029b1f05 _PyDict_DelItem_KnownHash + 149\r\n6   org.python.python             \t0x0000000102a42deb _PyEval_EvalFrameDefault + 11755\r\n7   org.python.python             \t0x0000000102a49d76 _PyEval_EvalCodeWithName + 2422\r\n8   org.python.python             \t0x0000000102a3ff24 PyEval_EvalCode + 100\r\n9   org.python.python             \t0x0000000102a7d301 PyRun_FileExFlags + 209\r\n10  org.python.python             \t0x0000000102a7cbab PyRun_SimpleFileExFlags + 859\r\n11  org.python.python             \t0x0000000102a9ac0c pymain_main + 8060\r\n12  org.python.python             \t0x0000000102a9b071 _Py_UnixMain + 129\r\n13  libdyld.dylib                 \t0x00007fff51d7a015 start + 1\r\n```\r\n\r\nIf we remove *both* `del` lines, it will crash under Python 3.7b4:\r\n```\r\nThread 0 Crashed:: Dispatch queue: com.apple.main-thread\r\n0   libsystem_kernel.dylib        \t0x00007fff51ecab6e __pthread_kill + 10\r\n1   libsystem_pthread.dylib       \t0x00007fff52095080 pthread_kill + 333\r\n2   libsystem_c.dylib             \t0x00007fff51dd86fe raise + 26\r\n3   libsystem_platform.dylib      \t0x00007fff52088f5a _sigtramp + 26\r\n4   ???                           \t0xcbcbcbcbcbcbcbcb 0 + 14685055086129564619\r\n5   org.python.python             \t0x000000010138d759 free_keys_object + 137\r\n6   org.python.python             \t0x000000010138fce3 dict_dealloc + 195\r\n7   org.python.python             \t0x000000010139c10c module_dealloc + 108\r\n8   org.python.python             \t0x000000010138cb7c insertdict + 572\r\n9   org.python.python             \t0x0000000101441ae3 PyImport_Cleanup + 1235\r\n10  org.python.python             \t0x000000010144ec56 Py_FinalizeEx + 214\r\n11  org.python.python             \t0x0000000101475507 pymain_main + 6263\r\n12  org.python.python             \t0x0000000101476071 _Py_UnixMain + 129\r\n13  libdyld.dylib                 \t0x00007fff51d7a015 start + 1\r\n```\r\n\r\nIf we remove *only* the `del e` line, leaving `del r` (deleting the `weakref.ref` object while the object it refers to is still alive) there is no crash.\r\n\r\nNone of these scenarios crash with Python 3.6 or Python 2.7.\r\n\r\nA similar test in pure-Python doesn't crash, so even though it's not clear to me if this is a CPython issue or a Cython issue, I'm starting here ðŸ˜„ (I couldn't find any related issues in the CPython bugtracker or this bugtracker)\r\n\r\n```python\r\n# Works fine\r\nfrom weakref import ref\r\nclass Base:\r\n    __slots__ = ()\r\n\r\nclass Derived(Base):\r\n    __slots__ = ('__weakref__',)\r\n\r\ne = Derived()\r\nr = ref(e)\r\ndel e\r\ndel r\r\n```",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "> None of these scenarios crash with Python 3.6 or Python 2.7.\r\n\r\nHmm, I take that back. Our CI service just [demonstrated a crash](https://travis-ci.org/gevent/gevent/jobs/379718754#L753) in CPython 3.6.4. I haven't produced it locally under 3.6.5 though.",
            "created_at": "2018-05-16T13:53:50Z",
            "html_url": "https://github.com/cython/cython/issues/2270#issuecomment-389526712",
            "id": 389526712,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2270",
            "node_id": "MDEyOklzc3VlQ29tbWVudDM4OTUyNjcxMg==",
            "updated_at": "2018-05-16T13:53:50Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/389526712",
            "user": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/1256082?v=4",
                "events_url": "https://api.github.com/users/jamadden/events{/privacy}",
                "followers_url": "https://api.github.com/users/jamadden/followers",
                "following_url": "https://api.github.com/users/jamadden/following{/other_user}",
                "gists_url": "https://api.github.com/users/jamadden/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jamadden",
                "id": 1256082,
                "login": "jamadden",
                "node_id": "MDQ6VXNlcjEyNTYwODI=",
                "organizations_url": "https://api.github.com/users/jamadden/orgs",
                "received_events_url": "https://api.github.com/users/jamadden/received_events",
                "repos_url": "https://api.github.com/users/jamadden/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jamadden/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jamadden/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jamadden"
            }
        }
    ],
    "comments": 1,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2270/comments",
    "created_at": "2018-05-16T13:25:14Z",
    "event_data": [
        {
            "actor": {
                "avatar_url": "https://avatars3.githubusercontent.com/u/1256082?v=4",
                "events_url": "https://api.github.com/users/jamadden/events{/privacy}",
                "followers_url": "https://api.github.com/users/jamadden/followers",
                "following_url": "https://api.github.com/users/jamadden/following{/other_user}",
                "gists_url": "https://api.github.com/users/jamadden/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jamadden",
                "id": 1256082,
                "login": "jamadden",
                "node_id": "MDQ6VXNlcjEyNTYwODI=",
                "organizations_url": "https://api.github.com/users/jamadden/orgs",
                "received_events_url": "https://api.github.com/users/jamadden/received_events",
                "repos_url": "https://api.github.com/users/jamadden/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jamadden/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jamadden/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jamadden"
            },
            "commit_id": "a6ee9283060e267c0a7a5f149f959ddc7318868f",
            "commit_url": "https://api.github.com/repos/gevent/gevent/commits/a6ee9283060e267c0a7a5f149f959ddc7318868f",
            "created_at": "2018-05-16T13:29:56Z",
            "event": "referenced",
            "id": 1629600843,
            "node_id": "MDE1OlJlZmVyZW5jZWRFdmVudDE2Mjk2MDA4NDM=",
            "url": "https://api.github.com/repos/cython/cython/issues/events/1629600843"
        }
    ],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2270/events",
    "html_url": "https://github.com/cython/cython/issues/2270",
    "id": 323619577,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2270/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzMjM2MTk1Nzc=",
    "number": 2270,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "__weakref__ in cdef subclasses crashes on Python 3.7b4 with Cython 0.28.2",
    "updated_at": "2018-05-16T13:53:50Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2270",
    "user": {
        "avatar_url": "https://avatars3.githubusercontent.com/u/1256082?v=4",
        "events_url": "https://api.github.com/users/jamadden/events{/privacy}",
        "followers_url": "https://api.github.com/users/jamadden/followers",
        "following_url": "https://api.github.com/users/jamadden/following{/other_user}",
        "gists_url": "https://api.github.com/users/jamadden/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jamadden",
        "id": 1256082,
        "login": "jamadden",
        "node_id": "MDQ6VXNlcjEyNTYwODI=",
        "organizations_url": "https://api.github.com/users/jamadden/orgs",
        "received_events_url": "https://api.github.com/users/jamadden/received_events",
        "repos_url": "https://api.github.com/users/jamadden/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jamadden/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jamadden/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jamadden"
    }
}