{
    "assignee": null,
    "assignees": [],
    "author_association": "NONE",
    "body": "Using Cython 0.28.4, I'm sometimes running into errors like the following when trying to compile files with type-annotated functions\r\n\r\ntext.pxd\r\n```\r\nimport cython\r\n\r\ncpdef fn(int version=?, unicode arg_name=?)\r\n```\r\n\r\ntest.py\r\n```\r\n# cython: language_level=3\r\ndef fn(\r\n    version: int=0,\r\n    arg_name: str='u'\r\n):\r\n    pass\r\n```\r\n\r\nOutput when trying to compile\r\n```\r\n>>>cython test.py\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n# cython: language_level=3\r\ndef fn(\r\n    version: int=0,\r\n    arg_name: str='u'\r\n   ^\r\n------------------------------------------------------------\r\n\r\ntest.py:4:4: Compiler crash in AnalyseDeclarationsTransform\r\n\r\nFile 'ModuleNode.py', line 123, in analyse_declarations: ModuleNode(test.py:1:0,\r\n    full_module_name = 'test')\r\nFile 'Nodes.py', line 427, in analyse_declarations: StatListNode(test.py:2:0)\r\nFile 'Nodes.py', line 2350, in analyse_declarations: CFuncDefNode(test.py:2:0,\r\n    modifiers = [...]/0,\r\n    overridable = 1,\r\n    visibility = 'private')\r\nFile 'Nodes.py', line 679, in analyse: CFuncDeclaratorNode(test.py:2:0,\r\n    calling_convention = '',\r\n    optional_arg_count = 1)\r\nFile 'Nodes.py', line 902, in analyse: CArgDeclNode(test.py:4:4,\r\n    is_generic = 1)\r\n\r\nCompiler crash traceback from this point on:\r\n  File \"<...>/Cython/Compiler/Nodes.py\", line 902, in analyse\r\n    if self.annotation and env and env.directives['annotation_typing'] and self.base_type.name is None:\r\nAttributeError: 'CAnalysedBaseTypeNode' object has no attribute 'name'\r\n```\r\n\r\nIf I remove the 2nd type annotation, I also get this error:\r\n```\r\n>>>cython test.py\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n# cython: language_level=3\r\ndef fn(\r\n    version: int=0,\r\n            ^\r\n------------------------------------------------------------\r\n\r\ntest.py:3:13: Signature does not agree with previous declaration\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n# cython: language_level=3\r\ndef fn(\r\n    version: int=0,\r\n            ^\r\n------------------------------------------------------------\r\n\r\ntest.py:3:13: Previous declaration here\r\n```\r\n\r\ni.e., with test.py as\r\n```\r\n# cython: language_level=3\r\ndef fn(\r\n    version: int=0,\r\n    arg_name='u'\r\n):\r\n    pass\r\n```",
    "closed_at": null,
    "comment_data": [],
    "comments": 0,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2487/comments",
    "created_at": "2018-07-10T21:05:51Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2487/events",
    "html_url": "https://github.com/cython/cython/issues/2487",
    "id": 340006950,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2487/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzNDAwMDY5NTA=",
    "number": 2487,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Errors compiling functions with type annotations",
    "updated_at": "2018-07-10T21:05:51Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2487",
    "user": {
        "avatar_url": "https://avatars0.githubusercontent.com/u/26908233?v=4",
        "events_url": "https://api.github.com/users/tbarrella/events{/privacy}",
        "followers_url": "https://api.github.com/users/tbarrella/followers",
        "following_url": "https://api.github.com/users/tbarrella/following{/other_user}",
        "gists_url": "https://api.github.com/users/tbarrella/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/tbarrella",
        "id": 26908233,
        "login": "tbarrella",
        "node_id": "MDQ6VXNlcjI2OTA4MjMz",
        "organizations_url": "https://api.github.com/users/tbarrella/orgs",
        "received_events_url": "https://api.github.com/users/tbarrella/received_events",
        "repos_url": "https://api.github.com/users/tbarrella/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/tbarrella/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/tbarrella/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/tbarrella"
    }
}