{
    "assignee": null,
    "assignees": [],
    "author_association": "CONTRIBUTOR",
    "body": "Given the code below, all of the functions compile except for `mysum2`.\r\n\r\n<details>\r\n\r\n```cython\r\ncdef double mysum0(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>len(a)):\r\n        r += a[i]\r\n    return r\r\n\r\n\r\ncdef double mysum1(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a)):\r\n        r += a[i]\r\n    return r\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n        r += a[i]\r\n    return r\r\n```\r\n\r\n</details>\r\n\r\n<br>\r\n\r\nThe errors generated by Cython for `mysum2` are as follows. \r\n\r\n<details>\r\n\r\n```\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n            ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:13: Coercion from Python not allowed without the GIL\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n            ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:13: Iterating over Python object not allowed without gil\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n                 ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:18: Calling gil-requiring function not allowed without gil\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n                 ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:18: Constructing Python tuple not allowed without gil\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n                  ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:19: Converting to Python object not allowed without gil\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n                             ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:30: Converting to Python object not allowed without gil\r\n\r\nError compiling Cython file:\r\n------------------------------------------------------------\r\n...\r\n\r\n\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i in range(<size_t>0, <size_t>len(a), <size_t>1):\r\n                                             ^\r\n------------------------------------------------------------\r\n\r\ntest_range.pyx:20:46: Converting to Python object not allowed without gil\r\n```\r\n\r\n</details>\r\n\r\n<br>\r\n\r\nDetails about the environment used below. This was run on my Mac, but expect the error to occur independently of the OS used.\r\n\r\n<details>\r\n\r\n```yaml\r\nname: cython\r\nchannels:\r\n  - conda-forge\r\n  - defaults\r\ndependencies:\r\n  - appdirs=1.4.3=py_1\r\n  - appnope=0.1.0=py36_0\r\n  - asn1crypto=0.24.0=py_1\r\n  - attrs=18.1.0=py_1\r\n  - automat=0.7.0=py36_0\r\n  - backcall=0.1.0=py_0\r\n  - blas=1.1=openblas\r\n  - bleach=2.1.3=py_0\r\n  - ca-certificates=2018.4.16=0\r\n  - certifi=2018.4.16=py36_0\r\n  - cffi=1.11.5=py36_0\r\n  - constantly=15.1.0=py_0\r\n  - cryptography=2.3=py36hdffb7b8_0\r\n  - cryptography-vectors=2.3=py36_0\r\n  - cython=0.28.4=py36hfc679d8_0\r\n  - decorator=4.3.0=py_0\r\n  - entrypoints=0.2.3=py36_1\r\n  - html5lib=1.0.1=py_0\r\n  - hyperlink=17.3.1=py_0\r\n  - idna=2.7=py36_2\r\n  - incremental=17.5.0=py_0\r\n  - ipykernel=4.8.2=py36_0\r\n  - ipython=6.4.0=py36_0\r\n  - ipython_genutils=0.2.0=py_1\r\n  - jedi=0.12.0=py36_0\r\n  - jinja2=2.10=py_1\r\n  - jsonschema=2.6.0=py36_1\r\n  - jupyter_client=5.2.3=py_1\r\n  - jupyter_core=4.4.0=py_0\r\n  - libffi=3.2.1=3\r\n  - libgfortran=3.0.0=0\r\n  - libsodium=1.0.16=0\r\n  - line_profiler=2.1.2=py36h470a237_1\r\n  - markupsafe=1.0=py36_0\r\n  - mistune=0.8.3=py36_1\r\n  - nbconvert=5.3.1=py_1\r\n  - nbformat=4.4.0=py_1\r\n  - ncurses=6.1=0\r\n  - notebook=5.6.0=py36_0\r\n  - numpy=1.14.5=py36_blas_openblashd3ea46f_201\r\n  - openblas=0.2.20=8\r\n  - openssl=1.0.2o=0\r\n  - pandoc=2.2.2=hde52d81_1\r\n  - pandocfilters=1.4.2=py_1\r\n  - parso=0.3.0=py_0\r\n  - pexpect=4.6.0=py36_0\r\n  - pickleshare=0.7.4=py36_0\r\n  - prometheus_client=0.3.0=py_0\r\n  - prompt_toolkit=1.0.15=py36_0\r\n  - ptyprocess=0.6.0=py36_0\r\n  - pyasn1=0.4.3=py_0\r\n  - pyasn1-modules=0.2.1=py_0\r\n  - pycparser=2.18=py_1\r\n  - pygments=2.2.0=py_1\r\n  - pyhamcrest=1.9.0=py_2\r\n  - pyopenssl=18.0.0=py36_0\r\n  - python=3.6.5=1\r\n  - python-dateutil=2.7.3=py_0\r\n  - pyzmq=17.1.0=py36hae99301_0\r\n  - readline=7.0=haf1bffa_1\r\n  - scipy=1.1.0=py36_blas_openblashd3ea46f_201\r\n  - send2trash=1.5.0=py_0\r\n  - service_identity=17.0.0=py_0\r\n  - setuptools=40.0.0=py36_0\r\n  - simplegeneric=0.8.1=py_1\r\n  - six=1.11.0=py36_1\r\n  - sqlite=3.20.1=0\r\n  - terminado=0.8.1=py36_0\r\n  - testpath=0.3.1=py36_0\r\n  - tk=8.6.8=0\r\n  - tornado=5.1=py36_0\r\n  - traitlets=4.3.2=py36_0\r\n  - wcwidth=0.1.7=py_1\r\n  - webencodings=0.5.1=py36_0\r\n  - xz=5.2.3=0\r\n  - zeromq=4.2.5=hfc679d8_4\r\n  - zlib=1.2.11=h470a237_3\r\n  - zope.interface=4.5.0=py36h470a237_0\r\n  - twisted=17.5.0=py36_0\r\n```\r\n\r\n</details>",
    "closed_at": null,
    "comment_data": [
        {
            "author_association": "CONTRIBUTOR",
            "body": "Should add that if `mysum2` is rewritten using the `for ... from ... by ...` (as shown below), this compiles fine.\r\n\r\n<details>\r\n\r\n```cython\r\ncdef double mysum2(double[:] a) nogil:\r\n    cdef size_t i\r\n    cdef double r = 0\r\n    for i from <size_t>0 <= i < <size_t>len(a) by <size_t>1:\r\n        r += a[i]\r\n    return r\r\n```\r\n\r\n</details>",
            "created_at": "2018-07-25T18:13:52Z",
            "html_url": "https://github.com/cython/cython/issues/2519#issuecomment-407847026",
            "id": 407847026,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2519",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQwNzg0NzAyNg==",
            "updated_at": "2018-07-25T18:13:52Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/407847026",
            "user": {
                "avatar_url": "https://avatars1.githubusercontent.com/u/3019665?v=4",
                "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
                "followers_url": "https://api.github.com/users/jakirkham/followers",
                "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
                "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/jakirkham",
                "id": 3019665,
                "login": "jakirkham",
                "node_id": "MDQ6VXNlcjMwMTk2NjU=",
                "organizations_url": "https://api.github.com/users/jakirkham/orgs",
                "received_events_url": "https://api.github.com/users/jakirkham/received_events",
                "repos_url": "https://api.github.com/users/jakirkham/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/jakirkham"
            }
        },
        {
            "author_association": "NONE",
            "body": "This is a known issue. When using `step`, Cython falls back to the python implementation of `range`. So the GIL must be acquired, which is against the `nogil` declaration. See #532 to track the progress of this issue.",
            "created_at": "2018-07-25T21:28:04Z",
            "html_url": "https://github.com/cython/cython/issues/2519#issuecomment-407901707",
            "id": 407901707,
            "issue_url": "https://api.github.com/repos/cython/cython/issues/2519",
            "node_id": "MDEyOklzc3VlQ29tbWVudDQwNzkwMTcwNw==",
            "updated_at": "2018-07-25T21:28:04Z",
            "url": "https://api.github.com/repos/cython/cython/issues/comments/407901707",
            "user": {
                "avatar_url": "https://avatars1.githubusercontent.com/u/12891691?v=4",
                "events_url": "https://api.github.com/users/gabrieldemarmiesse/events{/privacy}",
                "followers_url": "https://api.github.com/users/gabrieldemarmiesse/followers",
                "following_url": "https://api.github.com/users/gabrieldemarmiesse/following{/other_user}",
                "gists_url": "https://api.github.com/users/gabrieldemarmiesse/gists{/gist_id}",
                "gravatar_id": "",
                "html_url": "https://github.com/gabrieldemarmiesse",
                "id": 12891691,
                "login": "gabrieldemarmiesse",
                "node_id": "MDQ6VXNlcjEyODkxNjkx",
                "organizations_url": "https://api.github.com/users/gabrieldemarmiesse/orgs",
                "received_events_url": "https://api.github.com/users/gabrieldemarmiesse/received_events",
                "repos_url": "https://api.github.com/users/gabrieldemarmiesse/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/gabrieldemarmiesse/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/gabrieldemarmiesse/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/gabrieldemarmiesse"
            }
        }
    ],
    "comments": 2,
    "comments_url": "https://api.github.com/repos/cython/cython/issues/2519/comments",
    "created_at": "2018-07-25T17:59:21Z",
    "event_data": [],
    "events_url": "https://api.github.com/repos/cython/cython/issues/2519/events",
    "html_url": "https://github.com/cython/cython/issues/2519",
    "id": 344546888,
    "labels": [],
    "labels_url": "https://api.github.com/repos/cython/cython/issues/2519/labels{/name}",
    "locked": false,
    "milestone": null,
    "node_id": "MDU6SXNzdWUzNDQ1NDY4ODg=",
    "number": 2519,
    "repository_url": "https://api.github.com/repos/cython/cython",
    "state": "open",
    "title": "Cython range dislikes size_t step",
    "updated_at": "2018-07-25T21:28:05Z",
    "url": "https://api.github.com/repos/cython/cython/issues/2519",
    "user": {
        "avatar_url": "https://avatars1.githubusercontent.com/u/3019665?v=4",
        "events_url": "https://api.github.com/users/jakirkham/events{/privacy}",
        "followers_url": "https://api.github.com/users/jakirkham/followers",
        "following_url": "https://api.github.com/users/jakirkham/following{/other_user}",
        "gists_url": "https://api.github.com/users/jakirkham/gists{/gist_id}",
        "gravatar_id": "",
        "html_url": "https://github.com/jakirkham",
        "id": 3019665,
        "login": "jakirkham",
        "node_id": "MDQ6VXNlcjMwMTk2NjU=",
        "organizations_url": "https://api.github.com/users/jakirkham/orgs",
        "received_events_url": "https://api.github.com/users/jakirkham/received_events",
        "repos_url": "https://api.github.com/users/jakirkham/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/jakirkham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/jakirkham/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/jakirkham"
    }
}